[package]
name = "spider"
version = "0.1.0"
edition = "2021"

[dependencies]
reqwest = { version = "0.12.12", features = ["blocking"] }
scraper = "0.22.0"
clap = { version = "4.5.29", features = ["derive"] }
url = "2.5.4"
indicatif = "0.17.11"